# -*- coding: utf-8 -*-
"""Prototype content data. The 8 launch lines + a SAMPLE of the comparison sheet.

NOTE: CMP_FACTS values here are illustrative SAMPLE text for the design prototype — they are
line-agnostic general truths, clearly flagged "Sample" in the UI. The real, per-line, source-verified
values (with source URL + verified date, refreshed every 30 days) get loaded from the verified data
sheet during the facts-sourcing phase. Nothing here is presented as a verified per-line fact."""

LINES = [
    {"slug": "royal-caribbean", "emo": "🚢", "name": "Royal Caribbean",
     "cat": {"en": "Big-ship resort", "es": "Resort a bordo"},
     "tag": {"en": "Big, activity-packed ships for families and first-timers.",
             "es": "Barcos grandes y llenos de actividades para familias y primerizos."}},
    {"slug": "carnival", "emo": "🎉", "name": "Carnival",
     "cat": {"en": "Fun & value", "es": "Diversión y valor"},
     "tag": {"en": "Casual, fun-first cruising at an approachable pace.",
             "es": "Cruceros informales y divertidos, a un ritmo accesible."}},
    {"slug": "princess", "emo": "👑", "name": "Princess",
     "cat": {"en": "Relaxed premium", "es": "Premium relajado"},
     "tag": {"en": "Relaxed premium sailing with strong itineraries.",
             "es": "Navegación premium y relajada con excelentes itinerarios."}},
    {"slug": "celebrity", "emo": "🥂", "name": "Celebrity",
     "cat": {"en": "Premium modern", "es": "Premium moderno"},
     "tag": {"en": "Modern, adults-leaning ships with a refined feel.",
             "es": "Barcos modernos, orientados a adultos, con un toque refinado."}},
    {"slug": "holland-america", "emo": "⚓", "name": "Holland America",
     "cat": {"en": "Classic premium", "es": "Premium clásico"},
     "tag": {"en": "Classic, destination-focused cruising.",
             "es": "Cruceros clásicos, centrados en el destino."}},
    {"slug": "msc", "emo": "🌊", "name": "MSC Cruises",
     "cat": {"en": "European style", "es": "Estilo europeo"},
     "tag": {"en": "European style across a modern global fleet.",
             "es": "Estilo europeo en una flota global y moderna."}},
    {"slug": "cunard", "emo": "🎩", "name": "Cunard",
     "cat": {"en": "Ocean liner", "es": "Transatlántico"},
     "tag": {"en": "Ocean-liner tradition and formal elegance.",
             "es": "Tradición de transatlántico y elegancia formal."}},
    {"slug": "margaritaville-at-sea", "emo": "🏝️", "name": "Margaritaville at Sea",
     "cat": {"en": "Short getaways", "es": "Escapadas cortas"},
     "tag": {"en": "Laid-back, casual short getaways.",
             "es": "Escapadas cortas, informales y relajadas."}},
]

DESTINATIONS = [
    {"slug": "caribbean", "emo": "🏝️", "name": {"en": "Caribbean", "es": "Caribe"},
     "best": {"en": "Nov–Apr", "es": "Nov–Abr"}},
    {"slug": "bahamas", "emo": "⛵", "name": {"en": "Bahamas", "es": "Bahamas"},
     "best": {"en": "Year-round", "es": "Todo el año"}},
    {"slug": "alaska", "emo": "🏔️", "name": {"en": "Alaska", "es": "Alaska"},
     "best": {"en": "May–Sep", "es": "May–Sep"}},
    {"slug": "mediterranean", "emo": "🏛️", "name": {"en": "Mediterranean", "es": "Mediterráneo"},
     "best": {"en": "Apr–Oct", "es": "Abr–Oct"}},
    {"slug": "mexican-riviera", "emo": "🌵", "name": {"en": "Mexican Riviera", "es": "Riviera Mexicana"},
     "best": {"en": "Oct–Apr", "es": "Oct–Abr"}},
    {"slug": "panama-canal", "emo": "🛳️", "name": {"en": "Panama Canal", "es": "Canal de Panamá"},
     "best": {"en": "Oct–Apr", "es": "Oct–Abr"}},
    {"slug": "northern-europe", "emo": "🏰", "name": {"en": "Northern Europe", "es": "Norte de Europa"},
     "best": {"en": "May–Aug", "es": "May–Ago"}},
    {"slug": "hawaii", "emo": "🌺", "name": {"en": "Hawaii", "es": "Hawái"},
     "best": {"en": "Year-round", "es": "Todo el año"}},
    {"slug": "bermuda", "emo": "🐚", "name": {"en": "Bermuda", "es": "Bermudas"},
     "best": {"en": "Apr–Oct", "es": "Abr–Oct"}},
    {"slug": "canada-new-england", "emo": "🍁",
     "name": {"en": "Canada & New England", "es": "Canadá y Nueva Inglaterra"},
     "best": {"en": "May–Oct", "es": "May–Oct"}},
    {"slug": "pacific-coastal", "emo": "🌊",
     "name": {"en": "Pacific Coastal", "es": "Costa del Pacífico"},
     "best": {"en": "Spring & fall", "es": "Primavera y otoño"}},
    {"slug": "transatlantic", "emo": "⛴️", "name": {"en": "Transatlantic", "es": "Transatlántico"},
     "best": {"en": "Spring–fall", "es": "Primavera–otoño"}},
]

# Sample rows for the comparison-tool preview (illustrative, flagged Sample in UI)
CMP_FACTS = [
    {"label": {"en": "Daily gratuities", "es": "Propinas diarias"},
     "note": {"en": "Added automatically to your onboard account",
              "es": "Se añaden automáticamente a tu cuenta a bordo"},
     "a": {"en": "Added daily per guest — amount being verified",
           "es": "Diarias por huésped — monto en verificación"},
     "b": {"en": "Added daily per guest — amount being verified",
           "es": "Diarias por huésped — monto en verificación"}},
    {"label": {"en": "Drink package rule", "es": "Regla del paquete de bebidas"},
     "note": {"en": "The rule that surprises most guests",
              "es": "La regla que más sorprende a los huéspedes"},
     "a": {"en": "Typically all adults in the cabin must buy it",
           "es": "Normalmente todos los adultos del camarote deben comprarlo"},
     "b": {"en": "Typically all adults in the cabin must buy it",
           "es": "Normalmente todos los adultos del camarote deben comprarlo"}},
    {"label": {"en": "Wi-Fi", "es": "Wi-Fi"},
     "note": {"en": "Rarely included in the base fare",
              "es": "Rara vez incluido en la tarifa base"},
     "a": {"en": "Tiered packages, extra cost", "es": "Paquetes por niveles, costo adicional"},
     "b": {"en": "Tiered packages, extra cost", "es": "Paquetes por niveles, costo adicional"}},
    {"label": {"en": "Final payment", "es": "Pago final"},
     "note": {"en": "Miss it and the booking can cancel",
              "es": "Si lo pierdes, la reserva puede cancelarse"},
     "a": {"en": "Roughly 75–90 days before sailing", "es": "Aproximadamente 75–90 días antes de zarpar"},
     "b": {"en": "Roughly 75–90 days before sailing", "es": "Aproximadamente 75–90 días antes de zarpar"}},
    {"label": {"en": "Cancellation penalties", "es": "Penalidades de cancelación"},
     "note": {"en": "Increase as the sailing gets closer",
              "es": "Aumentan a medida que se acerca la salida"},
     "a": {"en": "Tiered schedule applies", "es": "Se aplica un calendario por tramos"},
     "b": {"en": "Tiered schedule applies", "es": "Se aplica un calendario por tramos"}},
    {"label": {"en": "Solo traveller supplement", "es": "Suplemento para viajero solo"},
     "note": {"en": "Solo cabins are limited and vary by ship",
              "es": "Los camarotes individuales son limitados y varían por barco"},
     "a": {"en": "Supplement usually applies", "es": "Suele aplicarse un suplemento"},
     "b": {"en": "Supplement usually applies", "es": "Suele aplicarse un suplemento"}},
]
